LIN 373 UTexas :: Jessy Li

Original material from Boris Ivanovic, Stanford CS 231A

## Linear Algebra in Numpy

Numpy is a supremely-optimized, well-maintained scientific computing package for Python. You will find numpy to be extremly useful for data analysis.

Suppose we have
```
    [1 2 3]
M = |4 5 6|
    [7 8 9]
    
    [1]
v = |2|
    [3]
```

### creating "arrays"

In [3]:
import numpy as np

M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

v = np.array([[1],
              [2],
              [3]])

## checking their dimensions

print(M.shape)
print(v.shape)


(3, 3)
(3, 1)


In [4]:
## creating a vector
v_single_dim = np.array([1,2,3])
print(v_single_dim.shape)

(3,)


In [5]:
## transposition
v.T

array([[1, 2, 3]])

In [6]:
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
v.T == v_single_dim

array([[ True,  True,  True]], dtype=bool)

In [8]:
v_single_dim.T

array([1, 2, 3])

In [9]:
## other ways to create matrices and vectors

## create an array of all zeros
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [11]:
## ... and all ones
np.ones((1,2))

array([[ 1.,  1.]])

In [12]:
## ... and a constent array
np.full((2,2),7)

/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 7.,  7.],
       [ 7.,  7.]])

In [13]:
## ... and an identity matrix
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [15]:
## ... and a random array
np.random.random((2,2))

array([[ 0.51786559,  0.74225407],
       [ 0.24050192,  0.47396242]])

In [17]:
## "stacking" arrays
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.array([7,8,9])
np.vstack([v1,v2,v3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
## What does this do?
M2 = np.hstack([v1,v2,v3])
print(M2)

[1 2 3 4 5 6 7 8 9]


### indexing

In [19]:
## accessing the first row
M[0]

array([1, 2, 3])

In [20]:
## accessing the second column
M[:,1]
# all the rows : but only second column

array([2, 5, 8])

In [26]:
## accessing the upper right 2x2 squared matrix
M[:2,1:3]

array([[2, 3],
       [5, 6]])

...back to slides...

### operations

In [22]:
## addition


array([[2],
       [4],
       [6]])

array([[3],
       [6],
       [9]])

In [24]:
## scalar multiplication


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [34]:
## matrix multiplication


array([[14],
       [32],
       [50]])

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

[[14]]


[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [40]:
## element-wise multiplication



array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])